#!/usr/bin/python2
from HTMLParser import HTMLParser
import sys

class ProblemsHTMLParser(HTMLParser):
	problems = set()
	exit_code = 0
	exit_codes = { 'critical': 2, 'warning': 1, 'unknown': 3 }

	# Parser state
	is_parsing = None
	in_node = False
	post_a = 0

	# Ignore warnings from the following Munin
	ignore = []

	def handle_starttag(self, tag, attrs):
		attrs = dict(attrs)

		if self.is_parsing: # Inside one of the .problem divs
			if self.in_node: # Inside one of the .nodetitle spans
				if tag == 'a':
					if self.post_a == 2: # Inside the third a
						if sys.argv[1] in attrs.get( 'href' ): # Match hostname
							problem = attrs.get( 'href' ).replace('.html', '')
							self.problems.add('%s:%s' % (self.is_parsing, problem))
							# Set exit code, whatever top is unless ignorable
							if not self.exit_code and not len(filter(lambda a: a in problem, self.ignore)):
								self.exit_code = self.exit_codes[self.is_parsing]
						self.in_node = False
						self.post_a = 0
						return
					else:
						self.post_a += 1
						return

			if tag == 'div' and attrs.get('class') == 'node':
				self.in_node = True
				return

		if tag == 'div' and attrs.get('class') == 'problem' and attrs.get('id', False):
			self.is_parsing = attrs.get('id') # Switch .problem div

parser = ProblemsHTMLParser()
try:
	parser.ignore = sys.argv[2].split(',')
except IndexError:
	pass
parser.feed(open('/var/cache/munin/www/problems.html', 'rb').read())

print('%d munin problem(s) for %s' % (len(parser.problems), sys.argv[1]))
if len(parser.problems):
	print('\n'.join(parser.problems))
if parser.exit_code: # There were issues
	sys.exit(parser.exit_code)
